var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__df53dbd0._.js")
R.c("server/chunks/ssr/_1e82cd47._.js")
R.c("server/chunks/ssr/656c9_next_dist_esm_build_templates_app-page_ab221f06.js")
R.c("server/chunks/ssr/[root-of-the-server]__272d0cef._.js")
R.c("server/chunks/ssr/[root-of-the-server]__120c57e8._.js")
R.c("server/chunks/ssr/656c9_next_dist_85fc7ecd._.js")
R.c("server/chunks/ssr/apps_web_src_app_dd37023f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__39a53cd5._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_4a203ccf._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_forbidden_50444f6c.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app__not-found_page_actions_3df07a96.js")
R.m(66978)
module.exports=R.m(66978).exports
