import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const globalForPrisma = global as unknown as { prisma: PrismaClient };
const prisma = globalForPrisma.prisma || new PrismaClient();
if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;

export async function GET() {
    try {
        const auditPages = [
            { path: '/zap/sections/atoms/border_radius/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/border_radius/inspector.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/color/InteractiveColorBox.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/color/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/elevation/body.tsx', category: 'Atoms', theme: 'Metro', layers: true, colors: false, fonts: true, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/elevation/inspector-actions.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/elevation/inspector-layer.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/elevation/inspector-universal.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/elevation/inspector.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/foundations/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/foundations/components.tsx', category: 'Atoms', theme: 'Metro', layers: true, colors: true, fonts: true, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/foundations/inspector.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/geometry/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/icons/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/interactive/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/layout/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/layout-grid/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/layout-grid/core-body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/layout-layers/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/motion/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/overlay/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/spacing/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/status/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/typography/DraggableToolbox.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/typography/body.tsx', category: 'Atoms', theme: 'Metro', layers: true, colors: true, fonts: true, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/typography/inspector.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/typography/playground-shell.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/atoms/typography/wild-preview.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/molecules/containment/CardsSection.tsx', category: 'Molecules', theme: 'Metro', layers: true, colors: false, fonts: false, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/molecules/containment/DialogsSection.tsx', category: 'Molecules', theme: 'Metro', layers: true, colors: false, fonts: false, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/molecules/containment/body.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/molecules/inputs/body.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/molecules/inputs/inspector.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/organisms/chat/interface.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/sections/organisms/settings/pane.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/activities/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/billing/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/border_radius/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/colors/index.tsx', category: 'Foundations', theme: 'Metro', layers: true, colors: false, fonts: true, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/colors/page.tsx', category: 'Foundations', theme: 'Metro', layers: true, colors: false, fonts: true, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/colors/page_backup.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/signin/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/dashboard/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/elevation/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/foundations/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/geometry/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/icons/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/kanban/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/l6_new_showcase/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/layout/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/login/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/motion/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/overlay/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/profile/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/settings/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/settings_demo/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/spacing/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/template/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/typography/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/zap/foundations/typography_goal/index.tsx', category: 'Foundations', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/accordion/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/avatar/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/badge/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/button/body.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/button/inspector.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/button/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/canvas/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/card/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/checkbox/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/colors/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/icons/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/indicator/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/input/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/interactive/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/label/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/layout/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/layout-layers/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/panel/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/pill/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/scroll-area/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            // search-input removed → consolidated into /atoms/input
            { path: '/app/design/zap/atoms/select/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/separator/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/skeleton/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/slider/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/status/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/switch/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/textarea/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/toggle/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/atoms/typography/page.tsx', category: 'Atoms', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/agents/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/stitch-brand-test/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/stitch-dropzone/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/stitch-playful-test/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/stitch-test/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/theme-remix/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/labs/theme-wix/page.tsx', category: 'Labs', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/m3-preview/m3-preview-dashboard.tsx', category: 'Unknown', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/m3-preview/page.tsx', category: 'Unknown', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/mission-control/page.tsx', category: 'Unknown', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/alert/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/breadcrumb/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/canvas-body/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            // card-number, currency-input, date-range-picker, input-otp, multi-select, phone-number, tag-input → consolidated into /molecules/inputs
            { path: '/app/design/zap/molecules/cards/page.tsx', category: 'Molecules', theme: 'Metro', layers: true, colors: false, fonts: false, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/dialog/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/dialogs/page.tsx', category: 'Molecules', theme: 'Metro', layers: true, colors: false, fonts: false, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/dropdown-menu/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/dropzone/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/form/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/forms/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/inputs/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/inspector-accordion/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/labeled-slider/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/layout/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/pagination/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/profile-switcher/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/progress/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/quick-navigate/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/rating/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            // removed select-date, select-time, service-selection
            { path: '/app/design/zap/molecules/steppers/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/tabs/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/theme-publisher/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/tooltip/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/molecules/user-session/page.tsx', category: 'Molecules', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/organisms/auth-scaffold/page.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/organisms/data-grid/page.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/organisms/interactive-gallery/page.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/organisms/kanban-board/page.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/organisms/navigation-menu/page.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/app/design/zap/organisms/user-profile-header/page.tsx', category: 'Organisms', theme: 'Metro', layers: false, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/data-display/PropertyBox.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/data-display/skeleton.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/data-display/table.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/formatters/credit-card.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/formatters/currency.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/formatters/phone.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/Icon.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/alert-circle.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/apple-core.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/apple.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/google-core.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/google.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/info.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/logo.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/icons/spinner.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/indicators/BadgePill.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/indicators/BreadcrumbPill.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/indicators/LiveBlinker.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/NavLink.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/SearchInput.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/Select.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/Tabs.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/Toggle.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/buttons.spec.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/buttons.tsx', category: 'Atoms', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/checkboxes.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/inputs.spec.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/inputs.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/slider.tsx', category: 'Atoms', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/switch.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/interactive/textarea.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/layout/AccordionItem.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/layout/box.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/layout/scroll-area.tsx', category: 'Atoms', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/layout/separator.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/layout/separators.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/status/avatars.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/status/badges.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/status/indicators.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/status/pills.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/surfaces/canvas.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/surfaces/card.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/surfaces/panel.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/surfaces/surface.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/typography/headings.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/typography/label.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/typography/mono.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/atoms/typography/text.tsx', category: 'Atoms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/cards/MetroFeatureCard.tsx', category: 'Molecules', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/layout/ThemeHeader.tsx', category: 'Molecules', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/layout/MetroHeader.tsx', category: 'Molecules', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/navigation/Breadcrumbs.tsx', category: 'Molecules', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/navigation/InspectorNav.tsx', category: 'Molecules', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/navigation/MainNavBar.tsx', category: 'Molecules', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/navigation/PlatformToggle.tsx', category: 'Molecules', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/molecules/navigation/SideNav.tsx', category: 'Molecules', theme: 'Core', layers: true, colors: false, fonts: true, icons: false, spacing: true, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/organisms/auth-scaffold.tsx', category: 'Organisms', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/organisms/data-grid.tsx', category: 'Organisms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/organisms/interactive-gallery.tsx', category: 'Organisms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/organisms/kanban-board.tsx', category: 'Organisms', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/organisms/navigation-menu.tsx', category: 'Organisms', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/organisms/user-profile-header.tsx', category: 'Organisms', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/layout/HorizontalNav.tsx', category: 'Unknown', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/layout/Inspector.tsx', category: 'Unknown', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/layout/MasterHorizontalShell.tsx', category: 'Unknown', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/layout/MasterVerticalShell.tsx', category: 'Unknown', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/layout/VerticalNav.tsx', category: 'Unknown', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/activities/ActivitiesTemplate.tsx', category: 'Templates', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/auth/auth-scaffold.tsx', category: 'Templates', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/billing/BillingTemplate.tsx', category: 'Templates', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/dashboard/DashboardTemplate.tsx', category: 'Templates', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/dashboard/app-shell.tsx', category: 'Templates', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/kanban/KanbanTemplate.tsx', category: 'Templates', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/login/LoginTemplate.tsx', category: 'Templates', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/profile/ProfileTemplate.tsx', category: 'Templates', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/settings/SettingsTemplate.tsx', category: 'Templates', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/genesis/templates/user-management/permissions/components/permission-list.tsx', category: 'Templates', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/accordion.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/ai-prompt-box.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/alert.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/avatar.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/badge.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/button.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/calendar.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/card.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/carousel.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/checkbox.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/command.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/date-picker.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/date-range-picker.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/dialog.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/dialogs/welcome-message-dialog.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/dropdown-menu.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/dropzone.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/empty-state.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/form.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/input-group.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/input-otp.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/input.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/label.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/labeled-slider.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/menubar.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/multi-select.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/navigation/navbar.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/navigation-menu.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/number-stepper.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/oauth-button-group.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/options-card.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/or-divider.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/page-menu.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/pagination.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/password-input-group.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/popover.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/profile-switcher.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/progress.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/quick-actions-dropdown.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/radio-group.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/rating.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/recaptcha-popover.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/resizable.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/scroll-area.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/select.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/separator.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/sheet.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/skeleton.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/slider.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/sonner.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/stepper.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/switch.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/table.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/tabs.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/tag-input.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/textarea.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/time-picker.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/toggle-group.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/toggle.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/toolbar.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/tooltip.tsx', category: 'Shadcn Core', theme: 'Core', layers: true, colors: true, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/user-hero.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: false, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false },
            { path: '/components/ui/user-session.tsx', category: 'Shadcn Core', theme: 'Core', layers: false, colors: false, fonts: true, icons: false, spacing: false, m3Mobile: false, m3Desktop: false, props: false }
        ];

        return NextResponse.json({
            pages: auditPages.map((page, index) => ({
                universalId: `gen-${index.toString().padStart(4, '0')}`,
                path: page.path,
                category: page.category,
                theme: page.theme,
                fonts: page.fonts,
                colors: page.colors,
                spacing: page.spacing,
                layers: page.layers,
                icons: page.icons,
                m3Mobile: page.m3Mobile,
                m3Desktop: page.m3Desktop,
                proofUrl: page.path.includes('dashboard') ? '/audit-proofs/metro_dashboard.png' : null,
                lastSync: new Date().toISOString(),
                createdAt: new Date().toISOString()
            })),
            components: []
        });
    } catch (error) {
        return NextResponse.json({ error: "Failed to fetch audit data", details: (error as Error).message }, { status: 500 });
    }
}
