import { runDiagnostic } from "../scripts/measure_health.js";
import { sendTelegramMessage } from "../platforms/telegram.js";
import "dotenv/config";

const ZEUS_TELEGRAM_ID = "8522264702"; // From OLYMPUS_SYS_OS_users

export async function runMsidReport() {
    console.log("📅 [MSID] Generating Daily 8:00 AM Health Report...");

    try {
        const report = await runDiagnostic();
        const emoji = report.score === 100 ? "✅" : (report.score > 70 ? "⚠️" : "❌");

        const message = [
            `**📅 DAILY MSID REPORT: "MAKING SURE IT'S DONE"**`,
            `---`,
            `**System Status:** ${emoji} ${report.score}/100`,
            `**Timestamp:** \`${report.timestamp.toLocaleString()}\``,
            ``,
            `**Health Breakdown:**`,
            report.records.length === 0
                ? `✨ All systems optimal. No issues detected.`
                : report.records.map(r => `• ${r}`).join("\n"),
            ``,
            `**Action items for today:**`,
            report.score === 100
                ? `• No immediate repairs needed. Proceed with planned builds.`
                : `• Review identified issues and run \`npm run health\` after fix.`,
            ``,
            `_Report generated by Jerry (Chief of Staff) via ZAP OS Daemon_`
        ].join("\n");

        await sendTelegramMessage(parseInt(ZEUS_TELEGRAM_ID), message);
        console.log("📅 [MSID] Report transmitted to Zeus.");
    } catch (error: any) {
        console.error("❌ [MSID] Failed to generate report:", error.message);
    }
}

// Support for direct execution
if (import.meta.url.endsWith(process.argv[1]!.replace(/\\/g, '/'))) {
    runMsidReport().catch(console.error);
}
