/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('fs');
const path = require('path');

/**
 * ZAP Theme Compiler
 * 
 * Takes a theme.json manifest (generated by the ZAP Theme Editor Inspector)
 * and compiles it into a scoped CSS override file ready for the Next.js cascade.
 */

function compileTheme(jsonString) {
    try {
        const manifest = JSON.parse(jsonString);

        if (!manifest.theme || !manifest.tokens) {
            throw new Error('Invalid theme manifest: Missing theme name or tokens.');
        }

        const themeName = manifest.theme.toLowerCase();
        const colors = manifest.tokens.colors;
        const physics = manifest.tokens.physics;

        // Ensure we build "!important" tags to override Tailwind defaults
        // while remaining confined strictly to the .theme-{name} scope.
        const cssContent = `/* 
    AUTO-GENERATED ZAP THEME OVERRIDE: ${themeName.toUpperCase()}
    Do not edit this file directly. 
    Modify via the ZAP Theme Editor UI inside the engine.
*/

.theme-${themeName} {
    /* --- Foundation Colors --- */
    --color-brand-midnight: ${colors.brand.midnight} !important;
    --color-brand-teal: ${colors.brand.teal} !important;
    --color-brand-yellow: ${colors.brand.yellow} !important;
    --color-brand-magenta: ${colors.brand.magenta} !important;
    --color-cream-white: ${colors.brand.cream} !important;

    /* --- Layer Semantics --- */
    --color-layer-canvas: ${colors.layers.canvas} !important;
    --color-layer-cover: ${colors.layers.cover} !important;
    --color-layer-panel: ${colors.layers.panel} !important;

    /* --- Physics & Bounds --- */
    --card-radius: ${physics.borderRadius} !important;
    --btn-radius: ${physics.borderRadius} !important;
    --input-radius: ${physics.borderRadius} !important;
    
    --card-border-width: ${physics.borderWidth} !important;
    --card-border: ${physics.shadows.color} !important;
    --input-border: ${physics.shadows.color} !important;

    /* --- Kinetic Shadows --- */
    --card-shadow: ${physics.shadows.offset} ${physics.shadows.offset} 0px 0px ${physics.shadows.color} !important;
}
`;

        return { themeName, cssContent, error: null };
    } catch (err) {
        return { error: err.message };
    }
}

// CLI Execution Wrapper
if (require.main === module) {
    const args = process.argv.slice(2);
    const inputPath = args[0];

    if (!inputPath) {
        console.error('Usage: node compile-theme.js <path-to-theme.json> [output-dir]');
        process.exit(1);
    }

    const resolvedInput = path.resolve(process.cwd(), inputPath);
    let outputDir = args[1]
        ? path.resolve(process.cwd(), args[1])
        : path.resolve(process.cwd(), 'src/themes');

    console.log(`[ZAP Compiler] Reading manifest from: ${resolvedInput}`);

    if (!fs.existsSync(resolvedInput)) {
        console.error(`[ZAP Compiler ERROR] File not found: ${resolvedInput}`);
        process.exit(1);
    }

    const jsonContent = fs.readFileSync(resolvedInput, 'utf-8');
    const { themeName, cssContent, error } = compileTheme(jsonContent);

    if (error) {
        console.error(`[ZAP Compiler ERROR] Compilation failed: ${error}`);
        process.exit(1);
    }

    // Ensure output directory exists based on theme name
    const finalOutputDir = path.join(outputDir, themeName.toUpperCase());
    if (!fs.existsSync(finalOutputDir)) {
        fs.mkdirSync(finalOutputDir, { recursive: true });
    }

    const outputPath = path.join(finalOutputDir, `theme-${themeName}.css`);
    fs.writeFileSync(outputPath, cssContent, 'utf-8');

    console.log(`[ZAP Compiler SUCCESS] Theme '${themeName}' compiled successfully!`);
    console.log(`[ZAP Compiler OUPUT] \u2192 ${outputPath}`);
}

module.exports = { compileTheme };
