import { themeFromSourceColor, hexFromArgb, argbFromHex } from "@material/material-color-utilities";
import * as fs from "fs";
import * as path from "path";

// The base seed color for the ZAP Engine (e.g., ZAP Yellow/Primary)
const SEED_COLOR_HEX = "#DFFF00"; // ZAP Acid Yellow

function generateTokens() {
    console.log(`Generating M3 Tokens from seed: ${SEED_COLOR_HEX}`);

    // Convert HEX to ARGB for the utility
    const seedArgb = argbFromHex(SEED_COLOR_HEX);

    // Generate the full M3 Theme (contains Light and Dark schemes + palettes)
    const theme = themeFromSourceColor(seedArgb);

    // Extract the standard Light Scheme
    const lightScheme = theme.schemes.light;

    // The material-color-utilities npm package (v0.4.0) sometimes doesn't have surface-container helpers
    // exposed cleanly on the base scheme export, so we grab them from the palettes directly.
    const neutralPalette = theme.palettes.neutral;

    // Map to our TOON-compatible structure
    const m3Colors = {
        primary: hexFromArgb(lightScheme.primary),
        "on-primary": hexFromArgb(lightScheme.onPrimary),
        "primary-container": hexFromArgb(lightScheme.primaryContainer),
        "on-primary-container": hexFromArgb(lightScheme.onPrimaryContainer),

        secondary: hexFromArgb(lightScheme.secondary),
        "on-secondary": hexFromArgb(lightScheme.onSecondary),
        "secondary-container": hexFromArgb(lightScheme.secondaryContainer),
        "on-secondary-container": hexFromArgb(lightScheme.onSecondaryContainer),

        tertiary: hexFromArgb(lightScheme.tertiary),
        "on-tertiary": hexFromArgb(lightScheme.onTertiary),
        "tertiary-container": hexFromArgb(lightScheme.tertiaryContainer),
        "on-tertiary-container": hexFromArgb(lightScheme.onTertiaryContainer),

        error: hexFromArgb(lightScheme.error),
        "on-error": hexFromArgb(lightScheme.onError),
        "error-container": hexFromArgb(lightScheme.errorContainer),
        "on-error-container": hexFromArgb(lightScheme.onErrorContainer),

        background: hexFromArgb(lightScheme.background),
        "on-background": hexFromArgb(lightScheme.onBackground),

        surface: hexFromArgb(lightScheme.surface),
        "on-surface": hexFromArgb(lightScheme.onSurface),
        "surface-variant": hexFromArgb(lightScheme.surfaceVariant),
        "on-surface-variant": hexFromArgb(lightScheme.onSurfaceVariant),

        outline: hexFromArgb(lightScheme.outline),
        "outline-variant": hexFromArgb(lightScheme.outlineVariant),

        // Surface Tonal Elevations 
        "surface-container-highest": hexFromArgb(neutralPalette.tone(90)),
        "surface-container-high": hexFromArgb(neutralPalette.tone(92)),
        "surface-container": hexFromArgb(neutralPalette.tone(94)),
        "surface-container-low": hexFromArgb(neutralPalette.tone(96)),
        "surface-container-lowest": hexFromArgb(neutralPalette.tone(100)),
    };

    // --- ZAP BRAND OVERRIDES ---
    // The M3 algorithm aggressively darkens pure yellows to ensure white text readability.
    // ZAP uses Black text on Yellow, meaning we must override M3's accessibility mutation
    // to preserve our brand identity while maintaining high contrast.
    console.log("Applying ZAP Brand token overrides (Primary: Acid Yellow, On-Primary: Black)");
    m3Colors["primary"] = SEED_COLOR_HEX;
    m3Colors["on-primary"] = "#000000";

    // Convert to TOON format (YAML-like)
    const contextDir = path.join(__dirname, "../../../.context");
    let toonOutput = `md:\n  sys:\n    color:\n`;
    for (const [key, val] of Object.entries(m3Colors)) {
        toonOutput += `      ${key}: "${val}"\n`;
    }
    const toonOutputPath = path.join(contextDir, "tokens.toon");

    // Create CSS Variables for Web
    let cssOutput = `/* auto-generated by m3-theme-generator */\n@layer base {\n  :root {\n`;
    for (const [key, val] of Object.entries(m3Colors)) {
        cssOutput += `    --md-sys-color-${key}: ${val};\n`;
    }
    cssOutput += `  }\n}\n`;
    const cssOutputPath = path.join(__dirname, "../src/styles/m3_tokens.css");

    // Ensure directories exist
    if (!fs.existsSync(contextDir)) {
        fs.mkdirSync(contextDir, { recursive: true });
    }
    const stylesDir = path.dirname(cssOutputPath);
    if (!fs.existsSync(stylesDir)) {
        fs.mkdirSync(stylesDir, { recursive: true });
    }

    // Write files
    fs.writeFileSync(toonOutputPath, toonOutput, "utf-8");
    fs.writeFileSync(cssOutputPath, cssOutput, "utf-8");

    console.log(`\n✅ M3 Tokens generated successfully!`);
    console.log(`TOON Context: ${toonOutputPath}`);
    console.log(`CSS Bridge: ${cssOutputPath}`);

    // Output a preview
    console.log("\nPreview (Light Scheme):");
    console.log(`Primary: ${m3Colors.primary}`);
    console.log(`Surface Container: ${m3Colors["surface-container"]}`);
}

generateTokens();
