'use client';

import { useTheme } from '../../../../../components/ThemeContext';
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MasterVerticalShell } from '../../../../../zap/layout/MasterVerticalShell';
import { Icon } from '../../../../../genesis/atoms/icons/Icon';
import { ContainerDevWrapper } from '../../../../../components/dev/ContainerDevWrapper';
import { fadeUp, spring, standardEase } from '../../../../../lib/animations';

export default function StitchDropzonePage() {
    const { devMode } = useTheme();
    const [rawHtml, setRawHtml] = useState<string>('');
    const [isPasted, setIsPasted] = useState<boolean>(false);

    const handlePaste = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        const val = e.target.value;
        setRawHtml(val);
        if (val.length > 50) {
            setIsPasted(true);
        } else {
            setIsPasted(false);
        }
    };

    const handleClear = () => {
        setRawHtml('');
        setIsPasted(false);
    };

    return (
        <MasterVerticalShell
            breadcrumbs={[
                { label: 'SYSTEMS' },
                { label: 'LAB' },
                { label: 'STITCH DROPZONE', active: true }
            ]}
            activeItem="Stitch Dropzone"
            inspectorTitle="Ingestion Protocol"
            inspectorContent={
                <div className="p-4 space-y-4 text-brand-midnight">
                    <div className="bg-layer-panel border-[length:var(--card-border-width,0px)] border-card-border p-4 shadow-card rounded-card">
                        <h4 className="font-bold uppercase text-label-small mb-2">Phase 1: Ingestion</h4>
                        <p className="text-label-medium font-medium leading-relaxed">
                            Paste raw HTML payloads generated by the Stitch MCP directly into the dropzone.
                            <br /><br />
                            Once ingested, the static markup will lock into the Left column, giving you a clean slate on the Right column to begin the ZAP Translation Wash using M3 Standards.
                        </p>
                    </div>
                </div>
            }
        >
            <div className="p-8 max-w-[1600px] font-display text-transform-primary space-y-12 text-brand-midnight">

                {/* Header Sequence */}
                <motion.div
                    initial="hidden"
                    animate="visible"
                    variants={fadeUp}
                    className="space-y-4 max-w-2xl"
                >
                    <h1 className="text-5xl font-black uppercase tracking-tighter leading-none">
                        Stitch Dropzone
                    </h1>
                    <p className="text-title-small font-medium text-iso-gray-500">
                        The designated ingestion bay for raw Stitch prototypes. Paste tailwind-heavy HTML to begin the variable wash.
                    </p>
                </motion.div>

                {/* Input Area (Transforms based on state) */}
                <AnimatePresence mode="popLayout">
                    {!isPasted ? (
                        <motion.div
                            key="input-zone"
                            initial={{ opacity: 0, scale: 0.95, y: 20 }}
                            animate={{ opacity: 1, scale: 1, y: 0 }}
                            exit={{ opacity: 0, scale: 0.95, y: -20, transition: standardEase }}
                            transition={spring}
                            className="w-full max-w-4xl"
                        >
                            <div className="relative group">
                                <div className="absolute -inset-1 bg-gradient-to-r from-brand-primary to-brand-magenta rounded-card blur opacity-25 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>
                                <div className="relative flex flex-col items-center justify-center p-12 bg-layer-canvas border-2 border-dashed border-iso-gray-400 rounded-card shadow-card focus-within:border-brand-magenta transition-colors">
                                    <Icon name="data_object" size={64} className="text-iso-gray-400 mb-6 group-focus-within:text-brand-magenta transition-colors" />
                                    <h3 className="text-title-large font-black mb-2">Paste Raw HTML Payload</h3>
                                    <p className="text-iso-gray-500 mb-8 font-medium">Ctrl+V / Cmd+V anywhere in the box below</p>

                                    <textarea
                                        value={rawHtml}
                                        onChange={handlePaste}
                                        placeholder="<div className='bg-[#bdf2d5] border-2...'>"
                                        className="w-full h-48 bg-layer-panel border-[length:var(--input-border-width,2px)] border-input-border rounded-input p-4 font-dev text-transform-tertiary text-body-small text-brand-midnight focus:outline-none focus:ring-4 focus:ring-brand-primary/50 shadow-btn resize-none"
                                    />
                                </div>
                            </div>
                        </motion.div>
                    ) : (
                        <motion.div
                            key="split-view"
                            initial={{ opacity: 0, y: 40 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={spring}
                            className="grid grid-cols-1 xl:grid-cols-2 gap-12 items-start"
                        >
                            {/* LEFT COLUMN: RAW STITCH */}
                            <div className="flex flex-col gap-4">
                                <div className="flex items-center justify-between border-b-[length:var(--card-border-width,2px)] border-card-border pb-2">
                                    <h2 className="text-title-medium font-black uppercase flex items-center gap-2 text-iso-gray-500">
                                        <Icon name="texture" size={24} />
                                        Raw Ingestion
                                    </h2>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={handleClear}
                                            className="text-label-small font-bold uppercase tracking-widest bg-iso-gray-600 text-white hover:bg-state-error px-3 py-1 rounded-[calc(var(--btn-radius)/2)] transition-colors"
                                        >
                                            Clear Canvas
                                        </button>
                                        <span className="text-label-small font-bold uppercase tracking-widest bg-iso-gray-200 text-iso-gray-600 px-2 py-1 rounded-[calc(var(--btn-radius)/2)]">Static</span>
                                    </div>
                                </div>

                                <div className="bg-layer-panel p-4 border-[length:var(--card-border-width,2px)] border-card-border rounded-card relative overflow-hidden flex justify-center shadow-card pointer-events-none opacity-80 scale-[0.9] origin-top">
                                    {/* Dangerously set the raw HTML so it renders EXACTLY as pasted */}
                                    <div dangerouslySetInnerHTML={{ __html: rawHtml }} className="w-full" />
                                </div>
                            </div>

                            {/* RIGHT COLUMN: ZAP TRANSLATION WORKSPACE */}
                            <motion.div
                                className="flex flex-col gap-4"
                                initial={{ opacity: 0, x: 20 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ ...spring, delay: 0.1 }}
                            >
                                <div className="flex items-center justify-between border-b-[length:var(--card-border-width,2px)] border-card-border pb-2">
                                    <h2 className="text-title-medium font-black uppercase flex items-center gap-2">
                                        <Icon name="precision_manufacturing" size={24} className="text-brand-magenta" />
                                        ZAP Translation (M3)
                                    </h2>
                                    <span className="text-label-small font-bold uppercase tracking-widest bg-brand-magenta text-white px-2 py-1 rounded-[calc(var(--btn-radius)/2)] animate-pulse">Washing Phase</span>
                                </div>

                                <ContainerDevWrapper showClassNames={devMode} identity={{ displayName: "Translation Canvas", filePath: "stitch-dropzone/page.tsx", type: "Workspace", architecture: "ZAP LAYOUT ENGINE" }}>
                                    <div className="bg-layer-cover p-8 border-[length:var(--card-border-width,2px)] border-card-border rounded-card flex flex-col items-center justify-center relative bg-[url('/grid.svg')] min-h-[500px]">

                                        <div className="text-center space-y-4 max-w-sm">
                                            <div className="w-16 h-16 bg-brand-primary rounded-full flex items-center justify-center mx-auto shadow-btn border-[length:var(--card-border-width,2px)] border-card-border">
                                                <Icon name="build_circle" size={32} className="text-brand-magenta" />
                                            </div>
                                            <h3 className="text-title-large font-black">Ready for M3 Wash</h3>
                                            <p className="text-iso-gray-500 font-medium">
                                                The raw layout has been locked. It&apos;s time to build the dynamic equivalent here using standard M3 / ZAP Global Tokens.
                                            </p>
                                            <ul className="text-body-small text-left bg-layer-panel p-4 rounded-card border-[length:var(--card-border-width,2px)] border-card-border font-dev text-transform-tertiary text-iso-gray-600 mt-4 space-y-2">
                                                <li><span className="text-brand-magenta px-1">•</span> bg-[#color] <span className="text-iso-gray-400">→</span> bg-surface</li>
                                                <li><span className="text-brand-magenta px-1">•</span> border-[#color] <span className="text-iso-gray-400">→</span> border-outline</li>
                                                <li><span className="text-brand-magenta px-1">•</span> rounded-[24px] <span className="text-iso-gray-400">→</span> rounded-card</li>
                                            </ul>
                                        </div>

                                    </div>
                                </ContainerDevWrapper>
                            </motion.div>
                        </motion.div>
                    )}
                </AnimatePresence>

            </div>
        </MasterVerticalShell>
    );
}

