import { Category } from '../services/category/category.model';
import { Brand } from '../services/brand/brand.model';
import { DiningOption } from '../services/dining-option/dining-option.model';
import { ModifierGroup } from '../services/modifier-group/modifier-group.model';
import { Product } from '../services/product/product.model';
import { GroupProduct } from '../services/group-product/group-product.model';
import { Unit } from '../services/unit/unit.model';
import { Location } from '../services/location/location.model';
import { Collection } from '../services/collection/collection.model';
import { Menu } from '../services/menu/menu.model';
import { ModifierItem } from '../services/modifier-item/modifier-item.model';
import { Customer } from '../services/customer/customer.model';
import { Membership } from '../services/membership/membership.model';
import { Promotion } from '../services/promotion/promotion.model';
import { Country } from '../services/country/country.model';

export const MOCK_CATEGORIES: Category[] = [
    { id: "1", name: "Iphone 16 Series", acronymn: "I1", slug: "/iphone-16", parent: "Electronics", item_count: 54, media_url: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
    { id: "2", name: "Samsung S24 Series", acronymn: "SS", slug: "/samsung-s24", parent: "Electronics", item_count: 32, media_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
    { id: "3", name: "Office Furniture", acronymn: "OF", slug: "/office-furniture", parent: "Furniture", item_count: 12, media_url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=256&h=256&auto=format&fit=crop", is_active: false },
    { id: "4", name: "Cloud Services", acronymn: "CS", slug: "/cloud-services", parent: "Software", item_count: 7, media_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
    { id: "5", name: "Home Audio", acronymn: "HA", slug: "/home-audio", parent: "Electronics", item_count: 24, media_url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
];

export const MOCK_BRANDS: Brand[] = [
    { id: "BRD001", name: "Apple", acronymn: "AP", status_id: 1, slug: "apple", logo_url: "https://images.unsplash.com/photo-1621330396173-e41b1cafd17f?w=256&h=256&auto=format&fit=crop", reference_id: "REF-APL-01", apply_item_count: 154 },
    { id: "BRD002", name: "Samsung", acronymn: "SA", status_id: 1, slug: "samsung", logo_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=256&h=256&auto=format&fit=crop", reference_id: "REF-SAM-02", apply_item_count: 89 },
    { id: "BRD003", name: "Logitech", acronymn: "LO", status_id: 2, slug: "logitech", logo_url: "https://images.unsplash.com/photo-1541140532154-b024d715b909?w=256&h=256&auto=format&fit=crop", reference_id: "REF-LOG-03", apply_item_count: 42 },
];

export const MOCK_DINING_OPTIONS: DiningOption[] = [
    { id: "1", name: "Dine In", acronymn: "DI", status: "Active", type: "DINE_IN" },
    { id: "2", name: "Takeaway", acronymn: "TA", status: "Active", type: "TAKE_AWAY" },
    { id: "3", name: "Delivery", acronymn: "DE", status: "Active", type: "DELIVERY" },
    { id: "4", name: "Pick-up", acronymn: "PI", status: "Active", type: "PICK UP" },
];

export const MOCK_MODIFIER_GROUPS: ModifierGroup[] = [
    { id: "1", name: "Size Options", acronymn: "SO", status: "Active", minSelect: 1, maxSelect: 1, options: [], display_type: "Radio", total_item: 3, locations: ["HQ-01", "WH-EAST"] },
    { id: "2", name: "Toppings", acronymn: "TO", status: "Active", minSelect: 0, maxSelect: 5, options: [], display_type: "Checkbox", total_item: 12, locations: ["HQ-01"] },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "uuid-1",
        image: "/products/iphone15.png",
        name: "iPhone 15 - Black", acronymn: "I1",
        sku: "APP-IP15-BLK",
        barcode: "194253456789",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 999.00,
        stock: 54,
        unit: "Piece",
        location: "WH-East",
        status: 1,
        subRows: [
            {
                id: "uuid-1-1",
                image: "/products/iphone15.png",
                name: "iPhone 15 - Black 128GB",
                sku: "APP-IP15-BLK-128",
                barcode: "194253456780",
                cate_name: "Electronics",
                productType: "PHYSICAL",
                price: 999.00,
                stock: 30,
                unit: "Piece",
                location: "WH-East",
                status: 1,
            },
            {
                id: "uuid-1-2",
                image: "/products/iphone15.png",
                name: "iPhone 15 - Black 256GB", acronymn: "I1",
                sku: "APP-IP15-BLK-256",
                barcode: "194253456781",
                cate_name: "Electronics",
                productType: "PHYSICAL",
                price: 1099.00,
                stock: 24,
                unit: "Piece",
                location: "WH-East",
                status: 1,
            },
        ],
    },
    {
        id: "uuid-2",
        image: "/products/s24.png",
        name: "Samsung Galaxy S24", acronymn: "SG",
        sku: "SAM-S24-WHT",
        barcode: "8806090123456",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 899.00,
        stock: 12,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-3",
        image: "/products/premium_sub.png",
        name: "Premium Subscription", acronymn: "PS",
        sku: "SUB-PRM-1YR",
        barcode: "N/A",
        cate_name: "Software",
        productType: "DIGITAL",
        price: 120.00,
        stock: 9999,
        unit: "Year",
        location: "Cloud",
        status: 1
    },
    {
        id: "uuid-4",
        image: "/products/it_consulting.png",
        name: "IT Consulting Hour", acronymn: "IC",
        sku: "SRV-IT-1HR",
        barcode: "N/A",
        cate_name: "Services",
        productType: "SERVICE",
        price: 150.00,
        stock: 100,
        unit: "Hour",
        location: "HQ",
        status: 0
    },
    {
        id: "uuid-5",
        image: "https://images.unsplash.com/photo-1517336710211-4d2450ad1e7c?w=256&h=256&auto=format&fit=crop",
        name: "MacBook Pro 16", acronymn: "MP",
        sku: "APP-MBP16-SLV",
        barcode: "194253987654",
        cate_name: "Computers",
        productType: "PHYSICAL",
        price: 2499.00,
        stock: 0,
        unit: "Piece",
        location: "WH-North",
        status: 0
    },
    {
        id: "uuid-6",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=256&h=256&auto=format&fit=crop",
        name: "Sony WH-1000XM5", acronymn: "SW",
        sku: "SON-XM5-BLK",
        barcode: "4548736132504",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 399.00,
        stock: 85,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-7",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=256&h=256&auto=format&fit=crop",
        name: "Classic Leather Watch", acronymn: "CL",
        sku: "WTC-LTH-BRN",
        barcode: "7508736132501",
        cate_name: "Accessories",
        productType: "PHYSICAL",
        price: 150.00,
        stock: 120,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-8",
        image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=256&h=256&auto=format&fit=crop",
        name: "Desk Lamp Pro", acronymn: "DL",
        sku: "FUR-LMP-DSK",
        barcode: "8208736132502",
        cate_name: "Office Furniture",
        productType: "PHYSICAL",
        price: 45.00,
        stock: 300,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-9",
        image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=256&h=256&auto=format&fit=crop",
        name: "Studio Microphone", acronymn: "SM",
        sku: "AUD-MIC-STD",
        barcode: "9108736132503",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 299.00,
        stock: 45,
        unit: "Piece",
        location: "WH-North",
        status: 1
    },
    {
        id: "uuid-10",
        image: "https://images.unsplash.com/photo-1611186871348-b1ec696e52c9?w=256&h=256&auto=format&fit=crop",
        name: "Mechanical Keyboard", acronymn: "MK",
        sku: "ACC-KBD-MCH",
        barcode: "1108736132504",
        cate_name: "Computers",
        productType: "PHYSICAL",
        price: 129.00,
        stock: 200,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-11",
        image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=256&h=256&auto=format&fit=crop",
        name: "Monitor 27 inch 4K", acronymn: "M2",
        sku: "CMP-MON-27",
        barcode: "1208736132505",
        cate_name: "Computers",
        productType: "PHYSICAL",
        price: 549.00,
        stock: 60,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-12",
        image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=256&h=256&auto=format&fit=crop",
        name: "Nike Air Max", acronymn: "NA",
        sku: "CLO-SH-NIKE",
        barcode: "1308736132506",
        cate_name: "Clothing",
        productType: "PHYSICAL",
        price: 180.00,
        stock: 50,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-13",
        image: "https://images.unsplash.com/photo-1585333127302-d29217281096?w=256&h=256&auto=format&fit=crop",
        name: "Creative Software Suite", acronymn: "CS",
        sku: "SOF-CRT-ANL",
        barcode: "N/A",
        cate_name: "Software",
        productType: "DIGITAL",
        price: 350.00,
        stock: 9999,
        unit: "Year",
        location: "Cloud",
        status: 1
    },
    {
        id: "uuid-14",
        image: "https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=256&h=256&auto=format&fit=crop",
        name: "Yoga Mat Pro", acronymn: "YM",
        sku: "SPT-YOG-MAT",
        barcode: "1408736132507",
        cate_name: "Sports",
        productType: "PHYSICAL",
        price: 35.00,
        stock: 500,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-15",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=256&h=256&auto=format&fit=crop",
        name: "Eames Office Chair", acronymn: "EO",
        sku: "FUR-CHR-EAM",
        barcode: "1508736132508",
        cate_name: "Office Furniture",
        productType: "PHYSICAL",
        price: 899.00,
        stock: 15,
        unit: "Piece",
        location: "HQ",
        status: 1
    },
    {
        id: "uuid-16",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=256&h=256&auto=format&fit=crop",
        name: "Ray-Ban Aviator", acronymn: "RA",
        sku: "ACC-SUN-RAY",
        barcode: "1608736132509",
        cate_name: "Accessories",
        productType: "PHYSICAL",
        price: 210.00,
        stock: 75,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-17",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=256&h=256&auto=format&fit=crop",
        name: "Fresh Garden Salad", acronymn: "FG",
        sku: "FOD-SAL-GRD",
        barcode: "N/A",
        cate_name: "Food",
        productType: "PHYSICAL",
        price: 12.50,
        stock: 100,
        unit: "Box",
        location: "HQ",
        status: 1
    },
    {
        id: "uuid-18",
        image: "https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=256&h=256&auto=format&fit=crop",
        name: "Organic Honey (500g)", acronymn: "OH",
        sku: "FOD-HNY-ORG",
        barcode: "1708736132510",
        cate_name: "Food",
        productType: "PHYSICAL",
        price: 24.00,
        stock: 150,
        unit: "Piece",
        location: "WH-North",
        status: 1
    },
    {
        id: "uuid-19",
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=256&h=256&auto=format&fit=crop",
        name: "Pixel 8 Pro", acronymn: "P8",
        sku: "GGL-PXL8-PRO",
        barcode: "1808736132511",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 899.00,
        stock: 40,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-20",
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=256&h=256&auto=format&fit=crop",
        name: "Business Strategy Course", acronymn: "BS",
        sku: "SRV-EDU-BSN",
        barcode: "N/A",
        cate_name: "Services",
        productType: "DIGITAL",
        price: 199.00,
        stock: 9999,
        unit: "Year",
        location: "Cloud",
        status: 1
    },
    {
        id: "uuid-21",
        image: "https://images.unsplash.com/photo-1491633582648-27942438b053?w=256&h=256&auto=format&fit=crop",
        name: "Canvas Backpack", acronymn: "CB",
        sku: "ACC-BAG-CAN",
        barcode: "1908736132512",
        cate_name: "Accessories",
        productType: "PHYSICAL",
        price: 65.00,
        stock: 250,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-22",
        image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=256&h=256&auto=format&fit=crop",
        name: "Instant Camera", acronymn: "IC",
        sku: "ELE-CAM-INS",
        barcode: "2008736132513",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 99.00,
        stock: 35,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-23",
        image: "https://images.unsplash.com/photo-1512499617640-c74ae3a49dd5?w=256&h=256&auto=format&fit=crop",
        name: "Wireless Mouse Pro", acronymn: "WM",
        sku: "ACC-MSE-WRL",
        barcode: "2108736132514",
        cate_name: "Computers",
        productType: "PHYSICAL",
        price: 79.00,
        stock: 400,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-24",
        image: "https://images.unsplash.com/photo-1512446816042-444d641267d4?w=256&h=256&auto=format&fit=crop",
        name: "Essential Oil Diffuser", acronymn: "EO",
        sku: "HOM-DIF-ESS",
        barcode: "2208736132515",
        cate_name: "Home Audio",
        productType: "PHYSICAL",
        price: 45.00,
        stock: 180,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-25",
        image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=256&h=256&auto=format&fit=crop",
        name: "Programming E-book", acronymn: "PE",
        sku: "DIG-EBK-PRG",
        barcode: "N/A",
        cate_name: "Software",
        productType: "DIGITAL",
        price: 29.99,
        stock: 9999,
        unit: "Piece",
        location: "Cloud",
        status: 1
    },
    {
        id: "uuid-26",
        image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=256&h=256&auto=format&fit=crop",
        name: "Security Camera System", acronymn: "SC",
        sku: "ELE-SEC-CAM",
        barcode: "2308736132516",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 499.00,
        stock: 25,
        unit: "Box",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-27",
        image: "https://images.unsplash.com/photo-1574634534894-89d7576c8259?w=256&h=256&auto=format&fit=crop",
        name: "Adjustable Dumbbells", acronymn: "AD",
        sku: "SPT-DMB-ADJ",
        barcode: "2408736132517",
        cate_name: "Sports",
        productType: "PHYSICAL",
        price: 249.00,
        stock: 20,
        unit: "Box",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-28",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=256&h=256&auto=format&fit=crop",
        name: "Designer Sunglasses", acronymn: "DS",
        sku: "ACC-SUN-DSN",
        barcode: "2508736132518",
        cate_name: "Accessories",
        productType: "PHYSICAL",
        price: 150.00,
        stock: 60,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-29",
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=256&h=256&auto=format&fit=crop",
        name: "Samsung Galaxy Buds", acronymn: "SG",
        sku: "SAM-BDS-PRO",
        barcode: "2608736132519",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 199.00,
        stock: 120,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-30",
        image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=256&h=256&auto=format&fit=crop",
        name: "Minimalist T-Shirt", acronymn: "MT",
        sku: "CLO-TSH-MIN",
        barcode: "2708736132520",
        cate_name: "Clothing",
        productType: "PHYSICAL",
        price: 25.00,
        stock: 500,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-31",
        image: "https://images.unsplash.com/photo-1560243563-062bff001d68?w=256&h=256&auto=format&fit=crop",
        name: "Standing Desk", acronymn: "SD",
        sku: "FUR-DSK-STD",
        barcode: "2808736132521",
        cate_name: "Office Furniture",
        productType: "PHYSICAL",
        price: 499.00,
        stock: 10,
        unit: "Box",
        location: "HQ",
        status: 1
    },
    {
        id: "uuid-32",
        image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=256&h=256&auto=format&fit=crop",
        name: "Laptop Sleeve 14", acronymn: "LS",
        sku: "ACC-LAP-SLV",
        barcode: "2908736132522",
        cate_name: "Accessories",
        productType: "PHYSICAL",
        price: 35.00,
        stock: 150,
        unit: "Piece",
        location: "WH-West",
        status: 1
    },
    {
        id: "uuid-33",
        image: "https://images.unsplash.com/photo-1615461066821-4384aa27448d?w=256&h=256&auto=format&fit=crop",
        name: "Gourmet Coffee Beans", acronymn: "GC",
        sku: "FOD-COF-GRM",
        barcode: "3008736132523",
        cate_name: "Food",
        productType: "PHYSICAL",
        price: 18.00,
        stock: 200,
        unit: "kg",
        location: "WH-North",
        status: 1
    },
    {
        id: "uuid-34",
        image: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=256&h=256&auto=format&fit=crop",
        name: "Power Bank 20000mAh", acronymn: "PB",
        sku: "ELE-PWR-BNK",
        barcode: "3108736132524",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 59.00,
        stock: 90,
        unit: "Piece",
        location: "WH-East",
        status: 1
    },
    {
        id: "uuid-35",
        image: "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?w=256&h=256&auto=format&fit=crop",
        name: "Professional Camera Lens", acronymn: "PC",
        sku: "ELE-CAM-LNS",
        barcode: "3208736132525",
        cate_name: "Electronics",
        productType: "PHYSICAL",
        price: 1200.00,
        stock: 8,
        unit: "Box",
        location: "WH-East",
        status: 1
    }
];

export const MOCK_UNITS: Unit[] = [
    {
        id: 31,
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "BOTTLE",
        name: "Chai",
        symbol: "btl",
        precision: 0,
        status_id: 2201,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        translations: []
    },
    {
        id: "40",
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "PACK",
        name: "Gói/Bao",
        symbol: "pack",
        precision: 0,
        status_id: 2201,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true
    },
    {
        id: "1",
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "KG",
        name: "Kilogram",
        symbol: "kg",
        precision: 2,
        status_id: 2201,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        serial_id: "UOM-001"
    },
    {
        id: "2",
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "GR",
        name: "Gram",
        symbol: "g",
        precision: 0,
        status_id: 2201,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        serial_id: "UOM-002"
    },
    {
        id: "3",
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "L",
        name: "Liter",
        symbol: "L",
        precision: 3,
        status_id: 2201,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        serial_id: "UOM-003"
    },
    {
        id: "4",
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "M",
        name: "Meter",
        symbol: "m",
        precision: 2,
        status_id: 2202,
        status_code: "INACTIVE",
        status_name: "Inactive",
        is_active: false,
        serial_id: "UOM-004"
    },
    {
        id: "5",
        tenant_id: "00000000-0000-0000-0000-000000000000",
        code: "PCS",
        name: "Piece",
        symbol: "pcs",
        precision: 0,
        status_id: 2201,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        serial_id: "UOM-005"
    }
];

export const MOCK_LOCATIONS: Location[] = [
    {
        id: "loc-1",
        tenant_id: "tenant-1",
        serial_id: 1,
        serial_number: "LOC-001",
        location_code: "HQ-01",
        node_id: null,
        legacy_id: "L-001",
        name: "Main Headquarters", acronymn: "MH",
        status_id: 1,
        status_code: "ACTIVE",
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        slug: "hq-01",
        business_name: "ZAP Global HQ",
        description: "Main office and central hub",
        location_type_id: 1,
        location_type_text: "Office",
        location_type_code: "OFFICE",
        location_type_color_code: "#4F46E5",
        address_line_1: "789 Enterprise Way",
        province_id: 1,
        province_name: "California",
        district_id: 1,
        district_name: "Silicon Valley",
        ward_id: 1,
        ward_name: "Palo Alto",
        city: "Palo Alto",
        state: "CA",
        country_id: 1,
        zipcode: "94301",
        phone_number: "+1 650-555-0123",
        email: "hq@zap.com",
        website: "https://zap.com",
        twitter: "@zap_hq",
        instagram: "zap_global",
        facebook: "zap.global",
        logo_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=256&h=256&auto=format&fit=crop",
        cover_image_url: null,
        brand_color: "#4F46E5",
        timezone: "America/Los_Angeles",
        operating_hours: null,
        transfer_account: null,
        transfer_tag: null,
        parent_location_id: null
    },
    {
        id: "loc-2",
        tenant_id: "tenant-1",
        serial_id: 2,
        serial_number: "LOC-002",
        location_code: "WH-EAST",
        node_id: null,
        legacy_id: "L-002",
        name: "East Coast Warehouse", acronymn: "EC",
        status_id: 1,
        status_code: "ACTIVE",
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        slug: "wh-east",
        business_name: "ZAP Logistics East",
        description: "Primary distribution center for the East Coast",
        location_type_id: 2,
        location_type_text: "Warehouse",
        location_type_code: "WAREHOUSE",
        location_type_color_code: "#10B981",
        address_line_1: "123 Port Road",
        province_id: 2,
        province_name: "New Jersey",
        district_id: 2,
        district_name: "Jersey City",
        ward_id: 2,
        ward_name: "Port Area",
        city: "Jersey City",
        state: "NJ",
        country_id: 1,
        zipcode: "07302",
        phone_number: "+1 201-555-0123",
        email: "wh-east@zap.com",
        website: null,
        twitter: null,
        instagram: null,
        facebook: null,
        logo_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=256&h=256&auto=format&fit=crop",
        cover_image_url: null,
        brand_color: "#10B981",
        timezone: "America/New_York",
        operating_hours: null,
        transfer_account: null,
        transfer_tag: null,
        parent_location_id: null
    },
    {
        id: "loc-3",
        tenant_id: "tenant-1",
        serial_id: 3,
        serial_number: "LOC-003",
        location_code: "RETAIL-01",
        node_id: null,
        legacy_id: "L-003",
        name: "Downtown Retail Store", acronymn: "DR",
        status_id: 0,
        status_code: "INACTIVE",
        is_active: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        slug: "retail-01",
        business_name: "ZAP Flagship Store",
        description: "Main retail location in the city center",
        location_type_id: 3,
        location_type_text: "Retail",
        location_type_code: "RETAIL",
        location_type_color_code: "#F59E0B",
        address_line_1: "456 Broadway",
        province_id: 3,
        province_name: "New York",
        district_id: 3,
        district_name: "Manhattan",
        ward_id: 3,
        ward_name: "SoHo",
        city: "New York",
        state: "NY",
        country_id: 1,
        zipcode: "10012",
        phone_number: "+1 212-555-0123",
        email: "retail-01@zap.com",
        website: null,
        twitter: null,
        instagram: "zap_soho",
        facebook: null,
        logo_url: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=256&h=256&auto=format&fit=crop",
        cover_image_url: null,
        brand_color: "#F59E0B",
        timezone: "America/New_York",
        operating_hours: null,
        transfer_account: null,
        transfer_tag: null,
        parent_location_id: null
    }
];

export const MOCK_GROUP_PRODUCTS: GroupProduct[] = [
    { id: "1", name: "Premium Electronics", acronymn: "PE", slug: "premium-electronics", parent: "Electronics", item_count: 15, media_url: "https://images.unsplash.com/photo-1498049794561-7780e7231661?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
    { id: "2", name: "Gaming Setup", acronymn: "GS", slug: "gaming-setup", parent: "Electronics", item_count: 8, media_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
    { id: "3", name: "Modern Office", acronymn: "MO", slug: "modern-office", parent: "Furniture", item_count: 12, media_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
    { id: "4", name: "Smart Home", acronymn: "SH", slug: "smart-home", parent: "Electronics", item_count: 22, media_url: "https://images.unsplash.com/photo-1558002038-103792e07a70?q=80&w=256&h=256&auto=format&fit=crop", is_active: false },
    { id: "5", name: "Designer Collection", acronymn: "DC", slug: "designer-collection", parent: "Fashion", item_count: 45, media_url: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=256&h=256&auto=format&fit=crop", is_active: true },
];

export const MOCK_COLLECTIONS: Collection[] = [
    {
        id: "272160e3-f2b4-4d9d-b8b6-d13ff1c27948",
        serial_id: 50085,
        name: "Combo Bữa Trưa Nhanh Gọn",
        image_url: "https://cdn.pho24.com.vn/collections/lunch.jpg",
        product_count: 0,
        status_id: 2001,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        locations: ['All branches']
    },
    {
        id: "2",
        serial_id: 50086,
        name: "Winter Collection 2024",
        image_url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=256&h=256&auto=format&fit=crop",
        product_count: 56,
        status_id: 2001,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        locations: ['HQ-01', 'WH-EAST']
    },
    {
        id: "3",
        serial_id: 50087,
        name: "Summer Hits",
        image_url: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?q=80&w=256&h=256&auto=format&fit=crop",
        product_count: 12,
        status_id: 2001,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        locations: ['HQ-01']
    },
    {
        id: "4",
        serial_id: 50088,
        name: "Autumn Vibes",
        image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=256&h=256&auto=format&fit=crop",
        product_count: 31,
        status_id: 2002,
        status_code: "INACTIVE",
        status_name: "Inactive",
        is_active: false,
        locations: ['WH-EAST']
    },
    {
        id: "5",
        serial_id: 50089,
        name: "Holiday Special",
        image_url: "https://images.unsplash.com/photo-1512909006721-3d6018887383?q=80&w=256&h=256&auto=format&fit=crop",
        product_count: 18,
        status_id: 2001,
        status_code: "ACTIVE",
        status_name: "Active",
        is_active: true,
        locations: ['All branches']
    },
];

export const MOCK_MENUS: Menu[] = [
    { id: "1", name: "Thực đơn Sáng", acronymn: "TĐ", is_active: true, locations: ["HQ-01", "WH-EAST"], channels: ["POS"], total_items: 24, status: "Active" },
    { id: "2", name: "Thực đơn Trưa", acronymn: "TĐ", is_active: true, locations: ["HQ-01"], channels: ["POS", "KIOSK", "APP"], total_items: 45, status: "Active" },
    { id: "3", name: "Thực đơn Tối", acronymn: "TĐ", is_active: true, locations: ["HQ-01", "WH-EAST"], channels: ["APP", "KIOSK"], total_items: 38, status: "Active" },
    { id: "4", name: "Thực đơn Cuối Tuần", acronymn: "TĐ", is_active: false, locations: ["WH-EAST"], channels: ["KIOSK", "WEB"], total_items: 12, status: "Inactive" },
    { id: "5", name: "Thực đơn Khuyến Mãi", acronymn: "TĐ", is_active: true, locations: ["HQ-01"], channels: ["KIOSK", "WEB"], total_items: 15, status: "Active" },
];

export const MOCK_MODIFIER_ITEMS: ModifierItem[] = [
    { id: "M01", name: "Thêm Trân Châu Trắng", acronymn: "TT", display_type: "Checkbox", locations: ["HQ-01", "WH-EAST"], price: 10000, is_active: true, status: "Active" },
    { id: "M02", name: "Thêm Trân Châu Đen", acronymn: "TT", display_type: "Checkbox", locations: ["HQ-01"], price: 8000, is_active: true, status: "Active" },
    { id: "M03", name: "Ít Đường", acronymn: "ÍĐ", display_type: "Radio", locations: ["HQ-01", "WH-EAST"], price: 0, is_active: true, status: "Active" },
    { id: "M04", name: "Không Đá", acronymn: "KĐ", display_type: "Radio", locations: ["WH-EAST"], price: 0, is_active: false, status: "Inactive" },
    { id: "M05", name: "Thêm Kem Cheese", acronymn: "TK", display_type: "Checkbox", locations: ["HQ-01"], price: 15000, is_active: true, status: "Active" },
];

export const MOCK_CUSTOMERS: Customer[] = [
    { id: 'CUST-001', name: 'Nguyễn Văn A', acronymn: "NV", phone: '0901234567', email: 'vana@gmail.com', money: 500000, point: 1250, membership: 'Gold', total_spend: 15000000, is_active: true },
    { id: 'CUST-002', name: 'Trần Thị B', acronymn: "TT", phone: '0912345678', email: 'thib@gmail.com', money: 25000, point: 450, membership: 'Silver', total_spend: 4200000, is_active: true },
    { id: 'CUST-003', name: 'Lê Văn C', acronymn: "LV", phone: '0987654321', email: 'vanc@gmail.com', money: 0, point: 100, membership: 'Bronze', total_spend: 1200000, is_active: false },
    { id: 'CUST-004', name: 'Phạm Thị D', acronymn: "PT", phone: '0933445566', email: 'thid@gmail.com', money: 1200000, point: 3200, membership: 'Diamond', total_spend: 45000000, is_active: true },
    { id: 'CUST-005', name: 'Hoàng Văn E', acronymn: "HV", phone: '0944556677', email: 'vane@gmail.com', money: 150000, point: 800, membership: 'Gold', total_spend: 8500000, is_active: true },
];

export const MOCK_MEMBERSHIPS: Membership[] = [
    {
        id: 'MEM-001',
        tier: 'Bronze', acronymn: "BR",
        tier_price: 0,
        billing_cycle: 'Monthly',
        benefit: '5% Point Cashback',
        is_active: true
    },
    {
        id: 'MEM-002',
        tier: 'Silver', acronymn: "SI",
        tier_price: 500000,
        billing_cycle: 'Monthly',
        benefit: '5% Discount, 7% Point Cashback',
        is_active: true
    },
    {
        id: 'MEM-003',
        tier: 'Gold', acronymn: "GO",
        tier_price: 1200000,
        billing_cycle: 'Monthly',
        benefit: '10% Discount, 10% Point Cashback, Free Shipping',
        is_active: true
    },
    {
        id: 'MEM-004',
        tier: 'Diamond', acronymn: "DI",
        tier_price: 5000000,
        billing_cycle: 'Yearly',
        benefit: '15% Discount, 15% Point Cashback, VIP Lounge, Personal Assistant',
        is_active: true
    },
    {
        id: 'MEM-005',
        tier: 'Enterprise', acronymn: "EN",
        tier_price: 15000000,
        billing_cycle: 'Yearly',
        benefit: 'Custom benefits, Unlimited users, Dedicated support',
        is_active: true
    }
];

export const MOCK_PROMOTIONS: Promotion[] = [
    { id: 'PROM-001', name: 'Summer Flash Sale', acronymn: "SF", discount_value: 15, discount_type: 'Percentage', apply_to: 'All products', schedule: 'Daily 14:00 - 16:00', locations: ['All branches'], is_active: true },
    { id: 'PROM-002', name: 'Grand Opening Discount', acronymn: "GO", discount_value: 50000, discount_type: 'Fixed', apply_to: 'Selected items', schedule: 'Mon, Wed, Fri', locations: ['HQ-01'], is_active: true },
    { id: 'PROM-003', name: 'Happy Hour Special', acronymn: "HH", discount_value: 20, discount_type: 'Percentage', apply_to: 'Drinks', schedule: 'Daily 17:00 - 19:00', locations: ['All branches'], is_active: true },
    { id: 'PROM-004', name: 'Weekend Brunch', acronymn: "WB", discount_value: 10, discount_type: 'Percentage', apply_to: 'Food', schedule: 'Sat, Sun 10:00 - 14:00', locations: ['HQ-01', 'WH-EAST'], is_active: false },
    { id: 'PROM-005', name: 'Member Anniversary', acronymn: "MA", discount_value: 20, discount_type: 'Percentage', apply_to: 'All products', schedule: 'Member Join Date', locations: ['All branches'], is_active: true },
];

export const MOCK_COUNTRIES: Country[] = [
    {
        id: "1",
        serial_id: 1,
        serial_number: "C-001",
        name: "Vietnam",
        code: "VN",
        iso_alpha2: "VN",
        iso_alpha3: "VNM",
        numeric_code: 704,
        phone_code: "+84",
        currency: "VND",
        flag_emoji: "🇻🇳",
        is_active: true,
        latitude: 14.0583,
        longitude: 108.2772,
        geometry_data: null,
        acronymn: "VN"
    },
    {
        id: "2",
        serial_id: 2,
        serial_number: "C-002",
        name: "United States",
        code: "US",
        iso_alpha2: "US",
        iso_alpha3: "USA",
        numeric_code: 840,
        phone_code: "+1",
        currency: "USD",
        flag_emoji: "🇺🇸",
        is_active: true,
        latitude: 37.0902,
        longitude: -95.7129,
        geometry_data: null,
        acronymn: "US"
    },
    {
        id: "3",
        serial_id: 3,
        serial_number: "C-003",
        name: "United Kingdom",
        code: "GB",
        iso_alpha2: "GB",
        iso_alpha3: "GBR",
        numeric_code: 826,
        phone_code: "+44",
        currency: "GBP",
        flag_emoji: "🇬🇧",
        is_active: true,
        latitude: 55.3781,
        longitude: -3.436,
        geometry_data: null,
        acronymn: "GB"
    },
    {
        id: "4",
        serial_id: 4,
        serial_number: "C-004",
        name: "Japan",
        code: "JP",
        iso_alpha2: "JP",
        iso_alpha3: "JPN",
        numeric_code: 392,
        phone_code: "+81",
        currency: "JPY",
        flag_emoji: "🇯🇵",
        is_active: true,
        latitude: 36.2048,
        longitude: 138.2529,
        geometry_data: null,
        acronymn: "JP"
    },
    {
        id: "5",
        serial_id: 5,
        serial_number: "C-005",
        name: "Singapore",
        code: "SG",
        iso_alpha2: "SG",
        iso_alpha3: "SGP",
        numeric_code: 702,
        phone_code: "+65",
        currency: "SGD",
        flag_emoji: "🇸🇬",
        is_active: true,
        latitude: 1.3521,
        longitude: 103.8198,
        geometry_data: null,
        acronymn: "SG"
    },
    {
        id: "6",
        serial_id: 6,
        serial_number: "C-006",
        name: "Germany",
        code: "DE",
        iso_alpha2: "DE",
        iso_alpha3: "DEU",
        numeric_code: 276,
        phone_code: "+49",
        currency: "EUR",
        flag_emoji: "🇩🇪",
        is_active: true,
        latitude: 51.1657,
        longitude: 10.4515,
        geometry_data: null,
        acronymn: "DE"
    },
    {
        id: "7",
        serial_id: 7,
        serial_number: "C-007",
        name: "France",
        code: "FR",
        iso_alpha2: "FR",
        iso_alpha3: "FRA",
        numeric_code: 250,
        phone_code: "+33",
        currency: "EUR",
        flag_emoji: "🇫🇷",
        is_active: true,
        latitude: 46.2276,
        longitude: 2.2137,
        geometry_data: null,
        acronymn: "FR"
    },
    {
        id: "8",
        serial_id: 8,
        serial_number: "C-008",
        name: "Australia",
        code: "AU",
        iso_alpha2: "AU",
        iso_alpha3: "AUS",
        numeric_code: 36,
        phone_code: "+61",
        currency: "AUD",
        flag_emoji: "🇦🇺",
        is_active: false,
        latitude: -25.2744,
        longitude: 133.7751,
        geometry_data: null,
        acronymn: "AU"
    },
    {
        id: "9",
        serial_id: 9,
        serial_number: "C-009",
        name: "South Korea",
        code: "KR",
        iso_alpha2: "KR",
        iso_alpha3: "KOR",
        numeric_code: 410,
        phone_code: "+82",
        currency: "KRW",
        flag_emoji: "🇰🇷",
        is_active: true,
        latitude: 35.9078,
        longitude: 127.7669,
        geometry_data: null,
        acronymn: "KR"
    },
    {
        id: "10",
        serial_id: 10,
        serial_number: "C-010",
        name: "Thailand",
        code: "TH",
        iso_alpha2: "TH",
        iso_alpha3: "THA",
        numeric_code: 764,
        phone_code: "+66",
        currency: "THB",
        flag_emoji: "🇹🇭",
        is_active: true,
        latitude: 15.87,
        longitude: 100.9925,
        geometry_data: null,
        acronymn: "TH"
    }
];