var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b11efac5._.js")
R.c("server/chunks/ssr/_1e82cd47._.js")
R.c("server/chunks/ssr/_4d3b33ed._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b4dd874b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d96cf157._.js")
R.c("server/chunks/ssr/656c9_next_dist_85fc7ecd._.js")
R.c("server/chunks/ssr/apps_web_src_app_dd37023f._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_global-error_72dd49f9.js")
R.c("server/chunks/ssr/[root-of-the-server]__39a53cd5._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_4a203ccf._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_forbidden_50444f6c.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_unauthorized_2b632d10.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_page_actions_ea579492.js")
R.c("server/chunks/ssr/[root-of-the-server]__07593bcd._.js")
R.m(55560)
module.exports=R.m(55560).exports
