var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__88a72707._.js")
R.c("server/chunks/ssr/_c507c955._.js")
R.c("server/chunks/ssr/_5f5b9c4a._.js")
R.c("server/chunks/ssr/_1e82cd47._.js")
R.c("server/chunks/ssr/[root-of-the-server]__eadeed8b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__120c57e8._.js")
R.c("server/chunks/ssr/656c9_next_dist_85fc7ecd._.js")
R.c("server/chunks/ssr/apps_web_src_app_dd37023f._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_global-error_72dd49f9.js")
R.c("server/chunks/ssr/[root-of-the-server]__39a53cd5._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_4a203ccf._.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_forbidden_50444f6c.js")
R.c("server/chunks/ssr/656c9_next_dist_client_components_builtin_unauthorized_2b632d10.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_page_actions_a0623280.js")
R.m(55560)
module.exports=R.m(55560).exports
