var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/ba147_next_dist_5717e4cd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f962aab9._.js")
R.c("server/chunks/ssr/ba147_next_dist_compiled_4284c3f5._.js")
R.c("server/chunks/ssr/ba147_next_dist_esm_7feccd28._.js")
R.c("server/chunks/ssr/ba147_next_dist_e752e768._.js")
R.c("server/chunks/ssr/5e5d0_@opentelemetry_api_build_esm_baa62026._.js")
R.c("server/chunks/ssr/69652_@swc_helpers_cjs__interop_require_wildcard_cjs_f6d64c6c._.js")
R.c("server/chunks/ssr/[externals]__f0336b73._.js")
R.c("server/chunks/ssr/apps_web_src_app_dd37023f._.js")
R.c("server/chunks/ssr/ba147_next_dist_client_components_builtin_global-error_dee8ae76.js")
R.c("server/chunks/ssr/[root-of-the-server]__33445e95._.js")
R.c("server/chunks/ssr/ba147_next_dist_client_components_a06ade30._.js")
R.c("server/chunks/ssr/ba147_next_dist_client_components_builtin_forbidden_723d348c.js")
R.c("server/chunks/ssr/ba147_next_dist_client_components_builtin_unauthorized_979b7e56.js")
<<<<<<< HEAD
R.c("server/chunks/ssr/[root-of-the-server]__f30d4278._.js")
R.c("server/chunks/ssr/_de8b7d23._.js")
=======
R.c("server/chunks/ssr/_46a61b90._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d11ac57e._.js")
>>>>>>> f7717326141b2f59363fa25d147f244a9701d7fb
R.m("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/apps/web/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/apps/web/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/apps/web/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/apps/web/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/apps/web/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/.pnpm/next@16.1.6_@babel+core@7.29.0_@opentelemetry+api@1.9.1_@playwright+test@1.58.2_react-dom@19._ulnomotjeano64m7sgwqzktrfy/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/apps/web/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
